### ISSUE TITLE
New fonts

### ISSUE THREAD

**Issue by superscratch444tre** [Secret-chest/fancy-text#1]
I found some new fonts: 
 
 - 𝒜𝐵𝒞𝒟𝐸𝐹𝒢𝐻𝐼𝒥𝒦𝐿𝑀𝒩𝓞𝒫𝒬𝑅𝒮𝒯𝒰𝒱𝒲𝒳𝒴𝒵𝒶𝒷𝒸𝒹𝑒𝒻𝑔𝒽𝒾𝒿𝓀𝓁𝓂𝓃𝓅𝓆𝓇𝓈𝓉𝓊𝓋𝓌𝓍𝓎𝓏 
 - 卂乃匚ᗪ乇千Ꮆ卄丨ﾌҜㄥ爪几ㄖ卩Ɋ尺丂ㄒㄩᐯ山乂ㄚ乙 (Uppercase only!)

**Comment by Secret-chest** [comment]
I have them already.

**Comment by Secret-chest** [comment]
No, I don't have the second one. I will add this.

**Comment by superscratch444tre** [comment]
The first one is different! look: 
yours: 𝓐𝓑𝓒𝓓𝓔𝓕𝓖𝓗𝓘𝓙𝓚𝓛𝓜𝓝𝓞𝓟𝓠𝓡𝓢𝓣𝓤𝓥𝓦𝓧𝓨𝓩𝓪𝓫𝓬𝓭𝓮𝓯𝓰𝓱𝓲𝓳𝓴𝓵𝓶𝓷𝓸𝓹𝓺𝓻𝓼𝓽𝓾𝓿𝔀𝔁𝔂𝔃
mine:  𝒜𝐵𝒞𝒟𝐸𝐹𝒢𝐻𝐼𝒥𝒦𝐿𝑀𝒩𝓞𝒫𝒬𝑅𝒮𝒯𝒰𝒱𝒲𝒳𝒴𝒵𝒶𝒷𝒸𝒹𝑒𝒻𝑔𝒽𝒾𝒿𝓀𝓁𝓂𝓃𝓸𝓅𝓆𝓇𝓈𝓉𝓊𝓋𝓌𝓍𝓎𝓏

**Comment by Secret-chest** [comment]
@superscratch444tre No. It is uselles. The same but with italic serifs intsead of some letters.

**Comment by superscratch444tre** [comment]
Ok, I deleted it. But look at the PR.

**Comment by superscratch444tre** [comment]
Oops, closed by mistake!

**Comment by Secret-chest** [comment]
> Ok, I deleted it. But look at the PR.

> @superscratch444tre Yes, it is very nice!
