### ISSUE TITLE
I made a python package

### ISSUE THREAD

**Issue by nottrobin** [Secret-chest/fancy-text#5]
Hiya.

Just to let you know, I made your code into a python package:

https://pypi.org/project/fancify-text/
https://github.com/nottrobin/fancify-text

``` bash
$ pip3 install fancify-text
$ fancify-bold "hello world"
𝗵𝗲𝗹𝗹𝗼 𝘄𝗼𝗿𝗹𝗱
```

If you want control of the module let me know, happy to give it to you. Also happy to keep maintaining it.

**Comment by Secret-chest** [comment]
I would like to mantain it. I have a much improved font database here: github.com/Secret-chest/unicode-fonts

**Comment by nottrobin** [comment]
OK do you want me to transfer the Github project to you? What about the Pypi module, would you like that? Where should I send it?

**Comment by Secret-chest** [comment]
> OK do you want me to transfer the Github project to you? What about the Pypi module, would you like that? Where should I send it?

I would like both. I am Secret-chest on both GitHub and PyPi.

**Comment by Secret-chest** [comment]
https://discuss.python.org/t/transferring-a-pypi-name-to-someone-else/7196 to transfer ownership to me

**Comment by nottrobin** [comment]
Done

**Comment by Secret-chest** [comment]
Thanks

**Comment by Secret-chest** [comment]
> Done

Jsut updated with the new fonts, thank you! You taught me how to package python modules 😀 (fyi almost everything on my github is an experiment)
